server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./fancydb
    username: electron
    password: 3f+r$OqU~'T!Iwh-
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs
    operations-sorter: method

api:
  info:
    title: Fancy Store API
    description: Fancy Store API Documentation
    version: 1.0.0
    terms-of-service: https://fancystore.io/terms
    contact:
     name: Fancy Store API Team
     email: apiteam@fancystore.io
     url: https://fancystore.io/team
    licence:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html