server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./fancydb
    username: electron
    password: 3f+r$OqU~'T!Iwh-
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs
    operations-sorter: method


